version: '3.8'

services:
  postgres:
    image: postgres:16.2
    container_name: postgres  # Explicit container naming
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistent storage
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d myappdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      app-network:
        aliases:
          - db  # Additional network alias

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin  # Explicit container naming
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app-network

  fastapi:
    build: .
    container_name: fastapi  # Explicit container naming
    volumes:
      - ./:/myapp/
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@postgres:5432/myappdb
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx  # Explicit container naming
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - app-network

  celeryworker:
    build: .
    container_name: celeryworker
    command: celery -A app.worker.celery worker --loglevel=info
    depends_on:
      - kafka
      - fastapi
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@postgres:5432/myappdb
      KAFKA_SERVER: kafka:9092
    networks:
      - app-network
      
  kafkaconsumer:
    build: .
    container_name: kafkaconsumer
    command: python app/worker/kafka_consumer_service.py
    depends_on:
      - kafka
      - fastapi
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@postgres:5432/myappdb
      KAFKA_SERVER: kafka:9092
    networks:
      - app-network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  app-network:
    driver: bridge